on:
  pull_request:
    types:
      - closed
    branches: [ main ]

jobs:

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      ## gitignore한 파일 생성해주기
      ## create application.properties
      - name: make application-aws.properties
        run: |
          cd ./src/main/resources
          touch ./application-dbconfig.properties
          # GitHub-Actions에서 설정한 값을 application-dev.properties 파일에 쓰기
          echo "${{ secrets.APPLICATION_DBCONFIG_PROPERTIES }}" > ./application-dbconfig.properties
        shell: bash

        #gradlew 파일 실행권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

        #빌드 시작
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        
        #프로젝트 zip파일로 압축
      - name: Make Zip File
        run: zip -qq -r ./build.zip .
        shell: bash

        #aws 접근 id, key
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

        # s3에 압축한 zip파일 업로드
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://awesomelydelicious/build/build.zip